// <auto-generated />
using System;
using BMG_Schedule.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BMG_Schedule.Migrations
{
    [DbContext(typeof(EmployeeManagerDbContext))]
    [Migration("20230220091131_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BMG_Schedule.Data.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Info")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Миглена",
                            LastName = "Велева"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Иван",
                            LastName = "Петров"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Никола",
                            LastName = "Попов"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Стефка",
                            LastName = "Стоянова"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Мария",
                            LastName = "Донева"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Георги",
                            LastName = "Митев"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Петър",
                            LastName = "Николов"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Павел",
                            LastName = "Попов"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Стоян",
                            LastName = "Константинов"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Галя",
                            LastName = "Стоянова"
                        });
                });

            modelBuilder.Entity("BMG_Schedule.Data.Models.RecordType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RecordTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Работен ден"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Командировка"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Отпуск - платен"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Отпуск - неплатен"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Болнични"
                        });
                });

            modelBuilder.Entity("BMG_Schedule.Data.Models.WorkingDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecordTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("WorkingDays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeId = 1,
                            End = new DateTime(2023, 2, 1, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 1, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            EmployeeId = 1,
                            End = new DateTime(2023, 2, 2, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 2, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            EmployeeId = 1,
                            End = new DateTime(2023, 2, 3, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 3, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            EmployeeId = 1,
                            End = new DateTime(2023, 2, 6, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 6, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            EmployeeId = 1,
                            End = new DateTime(2023, 2, 7, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 7, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            EmployeeId = 1,
                            End = new DateTime(2023, 2, 8, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 5,
                            Start = new DateTime(2023, 2, 8, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            EmployeeId = 1,
                            End = new DateTime(2023, 2, 9, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 5,
                            Start = new DateTime(2023, 2, 9, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            EmployeeId = 1,
                            End = new DateTime(2023, 2, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 5,
                            Start = new DateTime(2023, 2, 10, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            EmployeeId = 2,
                            End = new DateTime(2023, 2, 1, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 3,
                            Start = new DateTime(2023, 2, 1, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            EmployeeId = 2,
                            End = new DateTime(2023, 2, 2, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 3,
                            Start = new DateTime(2023, 2, 2, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            EmployeeId = 2,
                            End = new DateTime(2023, 2, 3, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 3, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            EmployeeId = 2,
                            End = new DateTime(2023, 2, 6, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 6, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            EmployeeId = 2,
                            End = new DateTime(2023, 2, 7, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 7, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            EmployeeId = 2,
                            End = new DateTime(2023, 2, 8, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 8, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            EmployeeId = 2,
                            End = new DateTime(2023, 2, 9, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 9, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            EmployeeId = 2,
                            End = new DateTime(2023, 2, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 10, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            EmployeeId = 3,
                            End = new DateTime(2023, 2, 1, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 1, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            EmployeeId = 3,
                            End = new DateTime(2023, 2, 2, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 2, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            EmployeeId = 3,
                            End = new DateTime(2023, 2, 3, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 3, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            EmployeeId = 3,
                            End = new DateTime(2023, 2, 6, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 6, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            EmployeeId = 3,
                            End = new DateTime(2023, 2, 7, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 4,
                            Start = new DateTime(2023, 2, 7, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            EmployeeId = 3,
                            End = new DateTime(2023, 2, 8, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 4,
                            Start = new DateTime(2023, 2, 8, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            EmployeeId = 3,
                            End = new DateTime(2023, 2, 9, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 9, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            EmployeeId = 3,
                            End = new DateTime(2023, 2, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 10, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            EmployeeId = 4,
                            End = new DateTime(2023, 2, 1, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 1, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            EmployeeId = 4,
                            End = new DateTime(2023, 2, 2, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 2, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            EmployeeId = 4,
                            End = new DateTime(2023, 2, 3, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 3, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            EmployeeId = 4,
                            End = new DateTime(2023, 2, 6, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 6, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            EmployeeId = 4,
                            End = new DateTime(2023, 2, 7, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 7, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            EmployeeId = 4,
                            End = new DateTime(2023, 2, 8, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 8, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            EmployeeId = 4,
                            End = new DateTime(2023, 2, 9, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 2,
                            Start = new DateTime(2023, 2, 9, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 32,
                            EmployeeId = 4,
                            End = new DateTime(2023, 2, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 10, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 33,
                            EmployeeId = 5,
                            End = new DateTime(2023, 2, 1, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 1, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 34,
                            EmployeeId = 5,
                            End = new DateTime(2023, 2, 2, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 2, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 35,
                            EmployeeId = 5,
                            End = new DateTime(2023, 2, 3, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 3, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 36,
                            EmployeeId = 5,
                            End = new DateTime(2023, 2, 6, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 6, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 37,
                            EmployeeId = 5,
                            End = new DateTime(2023, 2, 7, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 7, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 38,
                            EmployeeId = 5,
                            End = new DateTime(2023, 2, 8, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 8, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 39,
                            EmployeeId = 5,
                            End = new DateTime(2023, 2, 9, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 9, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 40,
                            EmployeeId = 5,
                            End = new DateTime(2023, 2, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 10, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 41,
                            EmployeeId = 6,
                            End = new DateTime(2023, 2, 1, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 1, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 42,
                            EmployeeId = 6,
                            End = new DateTime(2023, 2, 2, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 2, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 43,
                            EmployeeId = 6,
                            End = new DateTime(2023, 2, 3, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 3, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 44,
                            EmployeeId = 6,
                            End = new DateTime(2023, 2, 6, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 6, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 45,
                            EmployeeId = 6,
                            End = new DateTime(2023, 2, 7, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 7, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 46,
                            EmployeeId = 6,
                            End = new DateTime(2023, 2, 8, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 5,
                            Start = new DateTime(2023, 2, 8, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 47,
                            EmployeeId = 6,
                            End = new DateTime(2023, 2, 9, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 5,
                            Start = new DateTime(2023, 2, 9, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 48,
                            EmployeeId = 6,
                            End = new DateTime(2023, 2, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 5,
                            Start = new DateTime(2023, 2, 10, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 49,
                            EmployeeId = 7,
                            End = new DateTime(2023, 2, 1, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 3,
                            Start = new DateTime(2023, 2, 1, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 50,
                            EmployeeId = 7,
                            End = new DateTime(2023, 2, 2, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 3,
                            Start = new DateTime(2023, 2, 2, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 51,
                            EmployeeId = 7,
                            End = new DateTime(2023, 2, 3, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 3, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 52,
                            EmployeeId = 7,
                            End = new DateTime(2023, 2, 6, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 6, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 53,
                            EmployeeId = 7,
                            End = new DateTime(2023, 2, 7, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 7, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 54,
                            EmployeeId = 7,
                            End = new DateTime(2023, 2, 8, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 8, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 55,
                            EmployeeId = 7,
                            End = new DateTime(2023, 2, 9, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 9, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 56,
                            EmployeeId = 7,
                            End = new DateTime(2023, 2, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 10, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 57,
                            EmployeeId = 8,
                            End = new DateTime(2023, 2, 1, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 1, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 58,
                            EmployeeId = 8,
                            End = new DateTime(2023, 2, 2, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 2, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 59,
                            EmployeeId = 8,
                            End = new DateTime(2023, 2, 3, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 3, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 60,
                            EmployeeId = 8,
                            End = new DateTime(2023, 2, 6, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 6, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 61,
                            EmployeeId = 8,
                            End = new DateTime(2023, 2, 7, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 4,
                            Start = new DateTime(2023, 2, 7, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 62,
                            EmployeeId = 8,
                            End = new DateTime(2023, 2, 8, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 4,
                            Start = new DateTime(2023, 2, 8, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 63,
                            EmployeeId = 8,
                            End = new DateTime(2023, 2, 9, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 9, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 64,
                            EmployeeId = 8,
                            End = new DateTime(2023, 2, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 10, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 65,
                            EmployeeId = 9,
                            End = new DateTime(2023, 2, 1, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 1, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 66,
                            EmployeeId = 9,
                            End = new DateTime(2023, 2, 2, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 2, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 67,
                            EmployeeId = 9,
                            End = new DateTime(2023, 2, 3, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 3, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 68,
                            EmployeeId = 9,
                            End = new DateTime(2023, 2, 6, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 6, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 69,
                            EmployeeId = 9,
                            End = new DateTime(2023, 2, 7, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 7, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 70,
                            EmployeeId = 9,
                            End = new DateTime(2023, 2, 8, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 8, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 71,
                            EmployeeId = 9,
                            End = new DateTime(2023, 2, 9, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 2,
                            Start = new DateTime(2023, 2, 9, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 72,
                            EmployeeId = 9,
                            End = new DateTime(2023, 2, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 10, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 73,
                            EmployeeId = 10,
                            End = new DateTime(2023, 2, 1, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 1, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 74,
                            EmployeeId = 10,
                            End = new DateTime(2023, 2, 2, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 2, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 75,
                            EmployeeId = 10,
                            End = new DateTime(2023, 2, 3, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 3, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 76,
                            EmployeeId = 10,
                            End = new DateTime(2023, 2, 6, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 6, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 77,
                            EmployeeId = 10,
                            End = new DateTime(2023, 2, 7, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 7, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 78,
                            EmployeeId = 10,
                            End = new DateTime(2023, 2, 8, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 8, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 79,
                            EmployeeId = 10,
                            End = new DateTime(2023, 2, 9, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 9, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 80,
                            EmployeeId = 10,
                            End = new DateTime(2023, 2, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 10, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BMG_Schedule.Data.Models.WorkingDay", b =>
                {
                    b.HasOne("BMG_Schedule.Data.Models.Employee", null)
                        .WithMany("WorkingDays")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BMG_Schedule.Data.Models.Employee", b =>
                {
                    b.Navigation("WorkingDays");
                });
#pragma warning restore 612, 618
        }
    }
}
