// <auto-generated />
using BMG_Schedule.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BMG_Schedule.Migrations
{
    [DbContext(typeof(EmployeeManagerDbContext))]
    partial class EmployeeManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BMG_Schedule.Data.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Info")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Anna",
                            LastName = "Rockstar"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Julia",
                            LastName = "Developer"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Thomas",
                            LastName = "Huber"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Sara",
                            LastName = "Metroid"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Ben",
                            LastName = "Rockstar"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Alex",
                            LastName = "Rider"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Sophie",
                            LastName = "Ramos"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Julien",
                            LastName = "Russell"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Yvonne",
                            LastName = "Snider"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Jasmin",
                            LastName = "Curtis"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
