// <auto-generated />
using System;
using BMG_Schedule.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BMG_Schedule.Migrations
{
    [DbContext(typeof(EmployeeManagerDbContext))]
    partial class EmployeeManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BMG_Schedule.Data.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Info")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Миглена",
                            LastName = "Велева"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Иван",
                            LastName = "Петров"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Никола",
                            LastName = "Попов"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Стефка",
                            LastName = "Стоянова"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Мария",
                            LastName = "Донева"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Георги",
                            LastName = "Митев"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Петър",
                            LastName = "Николов"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Павел",
                            LastName = "Попов"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Стоян",
                            LastName = "Константинов"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Галя",
                            LastName = "Стоянова"
                        });
                });

            modelBuilder.Entity("BMG_Schedule.Data.Models.Exit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPersonal")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkingDayId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("WorkingDayId");

                    b.ToTable("Exits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            End = new DateTime(2023, 2, 1, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = true,
                            Reason = "",
                            Start = new DateTime(2023, 2, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 9
                        },
                        new
                        {
                            Id = 2,
                            End = new DateTime(2023, 2, 2, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = false,
                            Reason = "",
                            Start = new DateTime(2023, 2, 2, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 10
                        },
                        new
                        {
                            Id = 3,
                            End = new DateTime(2023, 2, 3, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = false,
                            Reason = "",
                            Start = new DateTime(2023, 2, 3, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 11
                        },
                        new
                        {
                            Id = 4,
                            End = new DateTime(2023, 2, 6, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = false,
                            Reason = "",
                            Start = new DateTime(2023, 2, 6, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 12
                        },
                        new
                        {
                            Id = 5,
                            End = new DateTime(2023, 2, 7, 13, 45, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = true,
                            Reason = "",
                            Start = new DateTime(2023, 2, 7, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 13
                        },
                        new
                        {
                            Id = 6,
                            End = new DateTime(2023, 1, 31, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = false,
                            Reason = "",
                            Start = new DateTime(2023, 1, 31, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 24
                        },
                        new
                        {
                            Id = 7,
                            End = new DateTime(2023, 2, 1, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = false,
                            Reason = "",
                            Start = new DateTime(2023, 2, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 25
                        },
                        new
                        {
                            Id = 8,
                            End = new DateTime(2023, 2, 2, 15, 52, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = true,
                            Reason = "",
                            Start = new DateTime(2023, 2, 2, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 26
                        },
                        new
                        {
                            Id = 9,
                            End = new DateTime(2023, 2, 3, 12, 43, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = false,
                            Reason = "",
                            Start = new DateTime(2023, 2, 3, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 27
                        },
                        new
                        {
                            Id = 10,
                            End = new DateTime(2023, 2, 8, 15, 28, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = false,
                            Reason = "",
                            Start = new DateTime(2023, 2, 8, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 30
                        },
                        new
                        {
                            Id = 11,
                            End = new DateTime(2022, 12, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = false,
                            Reason = "",
                            Start = new DateTime(2022, 12, 20, 9, 40, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 33
                        },
                        new
                        {
                            Id = 12,
                            End = new DateTime(2022, 12, 21, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = true,
                            Reason = "",
                            Start = new DateTime(2022, 12, 21, 12, 15, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 34
                        },
                        new
                        {
                            Id = 13,
                            End = new DateTime(2022, 12, 19, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = false,
                            Reason = "",
                            Start = new DateTime(2022, 12, 19, 13, 10, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 35
                        },
                        new
                        {
                            Id = 14,
                            End = new DateTime(2022, 12, 22, 16, 10, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = false,
                            Reason = "",
                            Start = new DateTime(2022, 12, 22, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 36
                        },
                        new
                        {
                            Id = 15,
                            End = new DateTime(2023, 1, 26, 11, 48, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = false,
                            Reason = "",
                            Start = new DateTime(2023, 1, 26, 10, 20, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 37
                        },
                        new
                        {
                            Id = 16,
                            End = new DateTime(2023, 2, 1, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = true,
                            Reason = "",
                            Start = new DateTime(2023, 2, 1, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 57
                        },
                        new
                        {
                            Id = 17,
                            End = new DateTime(2023, 2, 2, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = false,
                            Reason = "",
                            Start = new DateTime(2023, 2, 2, 12, 15, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 58
                        },
                        new
                        {
                            Id = 18,
                            End = new DateTime(2023, 2, 3, 14, 23, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = false,
                            Reason = "",
                            Start = new DateTime(2023, 2, 3, 13, 5, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 59
                        },
                        new
                        {
                            Id = 19,
                            End = new DateTime(2023, 2, 6, 12, 32, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = false,
                            Reason = "",
                            Start = new DateTime(2023, 2, 6, 11, 8, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 60
                        },
                        new
                        {
                            Id = 20,
                            End = new DateTime(2023, 2, 7, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = true,
                            Reason = "",
                            Start = new DateTime(2023, 2, 7, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 61
                        },
                        new
                        {
                            Id = 21,
                            End = new DateTime(2023, 2, 1, 13, 45, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = false,
                            Reason = "",
                            Start = new DateTime(2023, 2, 1, 12, 20, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 73
                        },
                        new
                        {
                            Id = 22,
                            End = new DateTime(2023, 2, 2, 11, 20, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = true,
                            Reason = "",
                            Start = new DateTime(2023, 2, 2, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 74
                        },
                        new
                        {
                            Id = 23,
                            End = new DateTime(2023, 2, 3, 11, 15, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = false,
                            Reason = "",
                            Start = new DateTime(2023, 2, 3, 10, 5, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 75
                        },
                        new
                        {
                            Id = 24,
                            End = new DateTime(2023, 2, 6, 12, 48, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = false,
                            Reason = "",
                            Start = new DateTime(2023, 2, 6, 11, 32, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 76
                        },
                        new
                        {
                            Id = 25,
                            End = new DateTime(2023, 2, 7, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = false,
                            Reason = "",
                            Start = new DateTime(2023, 2, 7, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 77
                        },
                        new
                        {
                            Id = 26,
                            End = new DateTime(2023, 2, 1, 11, 25, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = false,
                            Reason = "",
                            Start = new DateTime(2023, 2, 1, 10, 17, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 89
                        },
                        new
                        {
                            Id = 27,
                            End = new DateTime(2023, 2, 2, 14, 32, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = false,
                            Reason = "",
                            Start = new DateTime(2023, 2, 2, 11, 13, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 90
                        },
                        new
                        {
                            Id = 28,
                            End = new DateTime(2023, 2, 3, 12, 48, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = false,
                            Reason = "",
                            Start = new DateTime(2023, 2, 3, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 91
                        },
                        new
                        {
                            Id = 29,
                            End = new DateTime(2023, 2, 6, 15, 15, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = true,
                            Reason = "",
                            Start = new DateTime(2023, 2, 6, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 92
                        },
                        new
                        {
                            Id = 30,
                            End = new DateTime(2023, 2, 8, 15, 32, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = false,
                            Reason = "",
                            Start = new DateTime(2023, 2, 8, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 94
                        },
                        new
                        {
                            Id = 31,
                            End = new DateTime(2023, 2, 2, 12, 23, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = false,
                            Reason = "",
                            Start = new DateTime(2023, 2, 2, 9, 45, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 106
                        },
                        new
                        {
                            Id = 32,
                            End = new DateTime(2023, 2, 3, 11, 46, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = false,
                            Reason = "",
                            Start = new DateTime(2023, 2, 3, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 107
                        },
                        new
                        {
                            Id = 33,
                            End = new DateTime(2023, 2, 6, 14, 47, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = false,
                            Reason = "",
                            Start = new DateTime(2023, 2, 6, 13, 23, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 108
                        },
                        new
                        {
                            Id = 34,
                            End = new DateTime(2023, 2, 7, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = true,
                            Reason = "",
                            Start = new DateTime(2023, 2, 7, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 109
                        },
                        new
                        {
                            Id = 35,
                            End = new DateTime(2023, 2, 9, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = false,
                            Reason = "",
                            Start = new DateTime(2023, 2, 9, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 111
                        },
                        new
                        {
                            Id = 36,
                            End = new DateTime(2023, 1, 30, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = false,
                            Reason = "",
                            Start = new DateTime(2023, 1, 30, 9, 52, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 119
                        },
                        new
                        {
                            Id = 37,
                            End = new DateTime(2023, 1, 31, 13, 36, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = false,
                            Reason = "",
                            Start = new DateTime(2023, 1, 31, 11, 20, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 120
                        },
                        new
                        {
                            Id = 38,
                            End = new DateTime(2023, 2, 1, 13, 54, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = false,
                            Reason = "",
                            Start = new DateTime(2023, 2, 1, 11, 43, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 121
                        },
                        new
                        {
                            Id = 39,
                            End = new DateTime(2023, 2, 2, 10, 47, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = true,
                            Reason = "",
                            Start = new DateTime(2023, 2, 2, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 122
                        },
                        new
                        {
                            Id = 40,
                            End = new DateTime(2023, 2, 3, 12, 23, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = false,
                            Reason = "",
                            Start = new DateTime(2023, 2, 3, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 123
                        },
                        new
                        {
                            Id = 41,
                            End = new DateTime(2023, 2, 2, 12, 20, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = false,
                            Reason = "",
                            Start = new DateTime(2023, 2, 2, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 138
                        },
                        new
                        {
                            Id = 42,
                            End = new DateTime(2023, 2, 3, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = true,
                            Reason = "",
                            Start = new DateTime(2023, 2, 3, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 139
                        },
                        new
                        {
                            Id = 43,
                            End = new DateTime(2023, 2, 6, 13, 45, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = false,
                            Reason = "",
                            Start = new DateTime(2023, 2, 6, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 140
                        },
                        new
                        {
                            Id = 44,
                            End = new DateTime(2023, 2, 7, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = false,
                            Reason = "",
                            Start = new DateTime(2023, 2, 7, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 141
                        },
                        new
                        {
                            Id = 45,
                            End = new DateTime(2023, 2, 8, 12, 40, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = false,
                            Reason = "",
                            Start = new DateTime(2023, 2, 8, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 142
                        },
                        new
                        {
                            Id = 46,
                            End = new DateTime(2023, 2, 6, 11, 15, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = false,
                            Reason = "",
                            Start = new DateTime(2023, 2, 6, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 156
                        },
                        new
                        {
                            Id = 47,
                            End = new DateTime(2023, 2, 7, 12, 40, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = false,
                            Reason = "",
                            Start = new DateTime(2023, 2, 7, 11, 15, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 157
                        },
                        new
                        {
                            Id = 48,
                            End = new DateTime(2023, 2, 8, 15, 15, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = false,
                            Reason = "",
                            Start = new DateTime(2023, 2, 8, 14, 2, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 158
                        },
                        new
                        {
                            Id = 49,
                            End = new DateTime(2023, 2, 9, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = false,
                            Reason = "",
                            Start = new DateTime(2023, 2, 9, 13, 10, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 159
                        },
                        new
                        {
                            Id = 50,
                            End = new DateTime(2023, 2, 10, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            IsPersonal = true,
                            Reason = "",
                            Start = new DateTime(2023, 2, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkingDayId = 160
                        });
                });

            modelBuilder.Entity("BMG_Schedule.Data.Models.RecordType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RecordTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Работен ден"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Командировка"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Отпуск - платен"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Отпуск - неплатен"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Болнични"
                        });
                });

            modelBuilder.Entity("BMG_Schedule.Data.Models.WorkingDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecordTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("WorkingDays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeId = 1,
                            End = new DateTime(2022, 12, 20, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2022, 12, 20, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            EmployeeId = 1,
                            End = new DateTime(2022, 12, 21, 17, 40, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2022, 12, 21, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            EmployeeId = 1,
                            End = new DateTime(2022, 12, 19, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2022, 12, 19, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            EmployeeId = 1,
                            End = new DateTime(2022, 12, 22, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2022, 12, 22, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            EmployeeId = 1,
                            End = new DateTime(2023, 1, 26, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 1, 26, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            EmployeeId = 1,
                            End = new DateTime(2023, 1, 27, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 5,
                            Start = new DateTime(2023, 1, 27, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            EmployeeId = 1,
                            End = new DateTime(2023, 1, 30, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 5,
                            Start = new DateTime(2023, 1, 30, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            EmployeeId = 1,
                            End = new DateTime(2023, 1, 31, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 5,
                            Start = new DateTime(2023, 1, 31, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            EmployeeId = 1,
                            End = new DateTime(2023, 2, 1, 16, 50, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 1, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            EmployeeId = 1,
                            End = new DateTime(2023, 2, 2, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 2, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            EmployeeId = 1,
                            End = new DateTime(2023, 2, 3, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 3, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            EmployeeId = 1,
                            End = new DateTime(2023, 2, 6, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 6, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            EmployeeId = 1,
                            End = new DateTime(2023, 2, 7, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 7, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            EmployeeId = 1,
                            End = new DateTime(2023, 2, 8, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 5,
                            Start = new DateTime(2023, 2, 8, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            EmployeeId = 1,
                            End = new DateTime(2023, 2, 9, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 5,
                            Start = new DateTime(2023, 2, 9, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            EmployeeId = 1,
                            End = new DateTime(2023, 2, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 5,
                            Start = new DateTime(2023, 2, 10, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            EmployeeId = 2,
                            End = new DateTime(2022, 12, 20, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2022, 12, 20, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            EmployeeId = 2,
                            End = new DateTime(2022, 12, 21, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2022, 12, 21, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            EmployeeId = 2,
                            End = new DateTime(2022, 12, 19, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 3,
                            Start = new DateTime(2022, 12, 19, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            EmployeeId = 2,
                            End = new DateTime(2022, 12, 22, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 3,
                            Start = new DateTime(2022, 12, 22, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            EmployeeId = 2,
                            End = new DateTime(2023, 1, 26, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 1, 26, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            EmployeeId = 2,
                            End = new DateTime(2023, 1, 27, 16, 55, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 1, 27, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            EmployeeId = 2,
                            End = new DateTime(2023, 1, 30, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 2,
                            Start = new DateTime(2023, 1, 30, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            EmployeeId = 2,
                            End = new DateTime(2023, 1, 31, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 1, 31, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            EmployeeId = 2,
                            End = new DateTime(2023, 2, 1, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 1, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            EmployeeId = 2,
                            End = new DateTime(2023, 2, 2, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 2, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            EmployeeId = 2,
                            End = new DateTime(2023, 2, 3, 18, 20, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 3, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            EmployeeId = 2,
                            End = new DateTime(2023, 2, 6, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 5,
                            Start = new DateTime(2023, 2, 6, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            EmployeeId = 2,
                            End = new DateTime(2023, 2, 7, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 5,
                            Start = new DateTime(2023, 2, 7, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            EmployeeId = 2,
                            End = new DateTime(2023, 2, 8, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 8, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            EmployeeId = 2,
                            End = new DateTime(2023, 2, 9, 15, 48, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 9, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 32,
                            EmployeeId = 2,
                            End = new DateTime(2023, 2, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 10, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 33,
                            EmployeeId = 3,
                            End = new DateTime(2022, 12, 20, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2022, 12, 20, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 34,
                            EmployeeId = 3,
                            End = new DateTime(2022, 12, 21, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2022, 12, 21, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 35,
                            EmployeeId = 3,
                            End = new DateTime(2022, 12, 19, 17, 45, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2022, 12, 19, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 36,
                            EmployeeId = 3,
                            End = new DateTime(2022, 12, 22, 17, 55, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2022, 12, 22, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 37,
                            EmployeeId = 3,
                            End = new DateTime(2023, 1, 26, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 1, 26, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 38,
                            EmployeeId = 3,
                            End = new DateTime(2023, 1, 27, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 1, 27, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 39,
                            EmployeeId = 3,
                            End = new DateTime(2023, 1, 30, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 1, 30, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 40,
                            EmployeeId = 3,
                            End = new DateTime(2023, 1, 31, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 4,
                            Start = new DateTime(2023, 1, 31, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 41,
                            EmployeeId = 3,
                            End = new DateTime(2023, 2, 1, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 4,
                            Start = new DateTime(2023, 2, 1, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 42,
                            EmployeeId = 3,
                            End = new DateTime(2023, 2, 2, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 2, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 43,
                            EmployeeId = 3,
                            End = new DateTime(2023, 2, 3, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 3, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 44,
                            EmployeeId = 3,
                            End = new DateTime(2023, 2, 6, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 6, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 45,
                            EmployeeId = 3,
                            End = new DateTime(2023, 2, 7, 16, 10, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 7, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 46,
                            EmployeeId = 3,
                            End = new DateTime(2023, 2, 8, 16, 38, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 8, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 47,
                            EmployeeId = 3,
                            End = new DateTime(2023, 2, 9, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 5,
                            Start = new DateTime(2023, 2, 9, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 48,
                            EmployeeId = 3,
                            End = new DateTime(2023, 2, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 10, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 49,
                            EmployeeId = 4,
                            End = new DateTime(2022, 12, 20, 16, 42, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2022, 12, 20, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 50,
                            EmployeeId = 4,
                            End = new DateTime(2022, 12, 21, 18, 5, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2022, 12, 21, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 51,
                            EmployeeId = 4,
                            End = new DateTime(2022, 12, 19, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 2,
                            Start = new DateTime(2022, 12, 19, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 52,
                            EmployeeId = 4,
                            End = new DateTime(2022, 12, 22, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 2,
                            Start = new DateTime(2022, 12, 22, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 53,
                            EmployeeId = 4,
                            End = new DateTime(2023, 1, 26, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 1, 26, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 54,
                            EmployeeId = 4,
                            End = new DateTime(2023, 1, 27, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 1, 27, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 55,
                            EmployeeId = 4,
                            End = new DateTime(2023, 1, 30, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 1, 30, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 56,
                            EmployeeId = 4,
                            End = new DateTime(2023, 1, 31, 17, 23, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 1, 31, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 57,
                            EmployeeId = 4,
                            End = new DateTime(2023, 2, 1, 17, 56, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 1, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 58,
                            EmployeeId = 4,
                            End = new DateTime(2023, 2, 2, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 2, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 59,
                            EmployeeId = 4,
                            End = new DateTime(2023, 2, 3, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 3, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 60,
                            EmployeeId = 4,
                            End = new DateTime(2023, 2, 6, 18, 13, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 6, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 61,
                            EmployeeId = 4,
                            End = new DateTime(2023, 2, 7, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 7, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 62,
                            EmployeeId = 4,
                            End = new DateTime(2023, 2, 8, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 5,
                            Start = new DateTime(2023, 2, 8, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 63,
                            EmployeeId = 4,
                            End = new DateTime(2023, 2, 9, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 9, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 64,
                            EmployeeId = 4,
                            End = new DateTime(2023, 2, 10, 16, 33, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 10, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 65,
                            EmployeeId = 5,
                            End = new DateTime(2022, 12, 20, 18, 5, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2022, 12, 20, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 66,
                            EmployeeId = 5,
                            End = new DateTime(2022, 12, 21, 17, 45, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2022, 12, 21, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 67,
                            EmployeeId = 5,
                            End = new DateTime(2022, 12, 19, 17, 49, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2022, 12, 19, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 68,
                            EmployeeId = 5,
                            End = new DateTime(2022, 12, 22, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2022, 12, 22, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 69,
                            EmployeeId = 5,
                            End = new DateTime(2023, 1, 26, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 1, 26, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 70,
                            EmployeeId = 5,
                            End = new DateTime(2023, 1, 27, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 3,
                            Start = new DateTime(2023, 1, 27, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 71,
                            EmployeeId = 5,
                            End = new DateTime(2023, 1, 30, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 3,
                            Start = new DateTime(2023, 1, 30, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 72,
                            EmployeeId = 5,
                            End = new DateTime(2023, 1, 31, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 4,
                            Start = new DateTime(2023, 1, 31, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 73,
                            EmployeeId = 5,
                            End = new DateTime(2023, 2, 1, 18, 22, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 1, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 74,
                            EmployeeId = 5,
                            End = new DateTime(2023, 2, 2, 18, 9, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 2, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 75,
                            EmployeeId = 5,
                            End = new DateTime(2023, 2, 3, 17, 20, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 3, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 76,
                            EmployeeId = 5,
                            End = new DateTime(2023, 2, 6, 16, 39, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 6, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 77,
                            EmployeeId = 5,
                            End = new DateTime(2023, 2, 7, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 7, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 78,
                            EmployeeId = 5,
                            End = new DateTime(2023, 2, 8, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 5,
                            Start = new DateTime(2023, 2, 8, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 79,
                            EmployeeId = 5,
                            End = new DateTime(2023, 2, 9, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 9, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 80,
                            EmployeeId = 5,
                            End = new DateTime(2023, 2, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 10, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 81,
                            EmployeeId = 6,
                            End = new DateTime(2022, 12, 20, 18, 10, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2022, 12, 20, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 82,
                            EmployeeId = 6,
                            End = new DateTime(2022, 12, 21, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 2,
                            Start = new DateTime(2022, 12, 21, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 83,
                            EmployeeId = 6,
                            End = new DateTime(2022, 12, 19, 17, 40, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2022, 12, 19, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 84,
                            EmployeeId = 6,
                            End = new DateTime(2022, 12, 22, 17, 25, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2022, 12, 22, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 85,
                            EmployeeId = 6,
                            End = new DateTime(2023, 1, 26, 18, 20, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 1, 26, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 86,
                            EmployeeId = 6,
                            End = new DateTime(2023, 1, 27, 17, 15, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 1, 27, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 87,
                            EmployeeId = 6,
                            End = new DateTime(2023, 1, 30, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 5,
                            Start = new DateTime(2023, 1, 30, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 88,
                            EmployeeId = 6,
                            End = new DateTime(2023, 1, 31, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 5,
                            Start = new DateTime(2023, 1, 31, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 89,
                            EmployeeId = 6,
                            End = new DateTime(2023, 2, 1, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 1, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 90,
                            EmployeeId = 6,
                            End = new DateTime(2023, 2, 2, 17, 32, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 2, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 91,
                            EmployeeId = 6,
                            End = new DateTime(2023, 2, 3, 17, 40, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 3, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 92,
                            EmployeeId = 6,
                            End = new DateTime(2023, 2, 6, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 6, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 93,
                            EmployeeId = 6,
                            End = new DateTime(2023, 2, 7, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 3,
                            Start = new DateTime(2023, 2, 7, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 94,
                            EmployeeId = 6,
                            End = new DateTime(2023, 2, 8, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 8, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 95,
                            EmployeeId = 6,
                            End = new DateTime(2023, 2, 9, 18, 9, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 9, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 96,
                            EmployeeId = 6,
                            End = new DateTime(2023, 2, 10, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 10, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 97,
                            EmployeeId = 7,
                            End = new DateTime(2022, 12, 20, 18, 5, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2022, 12, 20, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 98,
                            EmployeeId = 7,
                            End = new DateTime(2022, 12, 21, 17, 18, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2022, 12, 21, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 99,
                            EmployeeId = 7,
                            End = new DateTime(2022, 12, 19, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 5,
                            Start = new DateTime(2022, 12, 19, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 100,
                            EmployeeId = 7,
                            End = new DateTime(2022, 12, 22, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 5,
                            Start = new DateTime(2022, 12, 22, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 101,
                            EmployeeId = 7,
                            End = new DateTime(2023, 1, 26, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 1, 26, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 102,
                            EmployeeId = 7,
                            End = new DateTime(2023, 1, 27, 16, 20, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 1, 27, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 103,
                            EmployeeId = 7,
                            End = new DateTime(2023, 1, 30, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 1, 30, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 104,
                            EmployeeId = 7,
                            End = new DateTime(2023, 1, 31, 18, 10, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 1, 31, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 105,
                            EmployeeId = 7,
                            End = new DateTime(2023, 2, 1, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 3,
                            Start = new DateTime(2023, 2, 1, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 106,
                            EmployeeId = 7,
                            End = new DateTime(2023, 2, 2, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 2, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 107,
                            EmployeeId = 7,
                            End = new DateTime(2023, 2, 3, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 3, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 108,
                            EmployeeId = 7,
                            End = new DateTime(2023, 2, 6, 17, 45, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 6, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 109,
                            EmployeeId = 7,
                            End = new DateTime(2023, 2, 7, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 7, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 110,
                            EmployeeId = 7,
                            End = new DateTime(2023, 2, 8, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 2,
                            Start = new DateTime(2023, 2, 8, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 111,
                            EmployeeId = 7,
                            End = new DateTime(2023, 2, 9, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 9, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 112,
                            EmployeeId = 7,
                            End = new DateTime(2023, 2, 10, 17, 15, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 10, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 113,
                            EmployeeId = 8,
                            End = new DateTime(2022, 12, 20, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2022, 12, 20, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 114,
                            EmployeeId = 8,
                            End = new DateTime(2022, 12, 21, 17, 20, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2022, 12, 21, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 115,
                            EmployeeId = 8,
                            End = new DateTime(2022, 12, 19, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 2,
                            Start = new DateTime(2022, 12, 19, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 116,
                            EmployeeId = 8,
                            End = new DateTime(2022, 12, 22, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2022, 12, 22, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 117,
                            EmployeeId = 8,
                            End = new DateTime(2023, 1, 26, 17, 45, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 1, 26, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 118,
                            EmployeeId = 8,
                            End = new DateTime(2023, 1, 27, 17, 55, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 1, 27, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 119,
                            EmployeeId = 8,
                            End = new DateTime(2023, 1, 30, 18, 10, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 1, 30, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 120,
                            EmployeeId = 8,
                            End = new DateTime(2023, 1, 31, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 1, 31, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 121,
                            EmployeeId = 8,
                            End = new DateTime(2023, 2, 1, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 1, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 122,
                            EmployeeId = 8,
                            End = new DateTime(2023, 2, 2, 15, 47, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 2, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 123,
                            EmployeeId = 8,
                            End = new DateTime(2023, 2, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 3, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 124,
                            EmployeeId = 8,
                            End = new DateTime(2023, 2, 6, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 3,
                            Start = new DateTime(2023, 2, 6, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 125,
                            EmployeeId = 8,
                            End = new DateTime(2023, 2, 7, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 3,
                            Start = new DateTime(2023, 2, 7, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 126,
                            EmployeeId = 8,
                            End = new DateTime(2023, 2, 8, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 4,
                            Start = new DateTime(2023, 2, 8, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 127,
                            EmployeeId = 8,
                            End = new DateTime(2023, 2, 9, 18, 20, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 9, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 128,
                            EmployeeId = 8,
                            End = new DateTime(2023, 2, 10, 18, 10, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 10, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 129,
                            EmployeeId = 9,
                            End = new DateTime(2022, 12, 20, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 5,
                            Start = new DateTime(2022, 12, 20, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 130,
                            EmployeeId = 9,
                            End = new DateTime(2022, 12, 21, 18, 2, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2022, 12, 21, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 131,
                            EmployeeId = 9,
                            End = new DateTime(2022, 12, 19, 17, 50, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2022, 12, 19, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 132,
                            EmployeeId = 9,
                            End = new DateTime(2022, 12, 22, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2022, 12, 22, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 133,
                            EmployeeId = 9,
                            End = new DateTime(2023, 1, 26, 16, 20, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 1, 26, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 134,
                            EmployeeId = 9,
                            End = new DateTime(2023, 1, 27, 17, 45, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 1, 27, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 135,
                            EmployeeId = 9,
                            End = new DateTime(2023, 1, 30, 17, 55, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 1, 30, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 136,
                            EmployeeId = 9,
                            End = new DateTime(2023, 1, 31, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 2,
                            Start = new DateTime(2023, 1, 31, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 137,
                            EmployeeId = 9,
                            End = new DateTime(2023, 2, 1, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 2,
                            Start = new DateTime(2023, 2, 1, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 138,
                            EmployeeId = 9,
                            End = new DateTime(2023, 2, 2, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 2, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 139,
                            EmployeeId = 9,
                            End = new DateTime(2023, 2, 3, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 3, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 140,
                            EmployeeId = 9,
                            End = new DateTime(2023, 2, 6, 18, 5, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 6, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 141,
                            EmployeeId = 9,
                            End = new DateTime(2023, 2, 7, 18, 20, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 7, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 142,
                            EmployeeId = 9,
                            End = new DateTime(2023, 2, 8, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 8, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 143,
                            EmployeeId = 9,
                            End = new DateTime(2023, 2, 9, 17, 18, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 9, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 144,
                            EmployeeId = 9,
                            End = new DateTime(2023, 2, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 3,
                            Start = new DateTime(2023, 2, 10, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 145,
                            EmployeeId = 10,
                            End = new DateTime(2022, 12, 20, 16, 10, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2022, 12, 20, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 146,
                            EmployeeId = 10,
                            End = new DateTime(2022, 12, 21, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2022, 12, 21, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 147,
                            EmployeeId = 10,
                            End = new DateTime(2022, 12, 19, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 5,
                            Start = new DateTime(2022, 12, 19, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 148,
                            EmployeeId = 10,
                            End = new DateTime(2022, 12, 22, 18, 10, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2022, 12, 22, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 149,
                            EmployeeId = 10,
                            End = new DateTime(2023, 1, 26, 18, 22, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 1, 26, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 150,
                            EmployeeId = 10,
                            End = new DateTime(2023, 1, 27, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 3,
                            Start = new DateTime(2023, 1, 27, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 151,
                            EmployeeId = 10,
                            End = new DateTime(2023, 1, 30, 17, 45, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 1, 30, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 152,
                            EmployeeId = 10,
                            End = new DateTime(2023, 1, 31, 17, 55, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 1, 31, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 153,
                            EmployeeId = 10,
                            End = new DateTime(2023, 2, 1, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 1, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 154,
                            EmployeeId = 10,
                            End = new DateTime(2023, 2, 2, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 4,
                            Start = new DateTime(2023, 2, 2, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 155,
                            EmployeeId = 10,
                            End = new DateTime(2023, 2, 3, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 4,
                            Start = new DateTime(2023, 2, 3, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 156,
                            EmployeeId = 10,
                            End = new DateTime(2023, 2, 6, 17, 15, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 6, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 157,
                            EmployeeId = 10,
                            End = new DateTime(2023, 2, 7, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 7, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 158,
                            EmployeeId = 10,
                            End = new DateTime(2023, 2, 8, 17, 45, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 8, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 159,
                            EmployeeId = 10,
                            End = new DateTime(2023, 2, 9, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 9, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 160,
                            EmployeeId = 10,
                            End = new DateTime(2023, 2, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordTypeId = 1,
                            Start = new DateTime(2023, 2, 10, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BMG_Schedule.Data.Models.Exit", b =>
                {
                    b.HasOne("BMG_Schedule.Data.Models.Employee", null)
                        .WithMany("Exits")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("BMG_Schedule.Data.Models.WorkingDay", null)
                        .WithMany("Exits")
                        .HasForeignKey("WorkingDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BMG_Schedule.Data.Models.WorkingDay", b =>
                {
                    b.HasOne("BMG_Schedule.Data.Models.Employee", null)
                        .WithMany("WorkingDays")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BMG_Schedule.Data.Models.Employee", b =>
                {
                    b.Navigation("Exits");

                    b.Navigation("WorkingDays");
                });

            modelBuilder.Entity("BMG_Schedule.Data.Models.WorkingDay", b =>
                {
                    b.Navigation("Exits");
                });
#pragma warning restore 612, 618
        }
    }
}
